---
- hosts: dev 
  vars:
     ansible_python_interpreter: /root/anaconda3/bin/python
  become: True // perché ho bisogno del sudo per installare un package di cui ho bisogno
  tasks:
    - name: Start the container
      docker_container:
        name: example-web
        image: francescogrossi/docker-ansible-demo:{{ DOCKER_TAG }}
        state: started
        recreate: yes
        detach: true
        ports:
          - "10080:8080"
