---
- hosts: dev 
  become: True // perché ho bisogno del sudo per installare un package di cui ho bisogno
tasks:
-	name: Install python pip
yum:
  name: python-pip
  state: present 
-	name: Install docker-py python module
pip:
  name: docker-py
  state: present 
-	name: Start the container
docker_container:
  name: app01-web
  image: francescogrossi/docker-ansible-demo:${DOCKER_TAG}
  state: started
  published_ports: 
    - 0.0.0.0:8080:8080
